package TestView;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JTextField;
import java.awt.FlowLayout;
import javax.swing.SwingUtilities;

public class Test extends JFrame {

  private static final long serialVersionUID = 1L;
  private JLabel label_a = new JLabel("Hello");
  private JLabel label_b = new JLabel("World!");
  private JButton button_a = new JButton("save");
  private JTextField textField_a = new JTextField("\"");


  public Test() {
    setTitle("Test");
    setLayout(new FlowLayout());
    setDefaultCloseOperation(EXIT_ON_CLOSE);

    // add labels 
    label_a.setVisible(true);
    add(label_a);
    label_b.setVisible(true);
    add(label_b);

    // add buttons 
    button_a.setVisible(true);
    add(button_a);

    // add text fields 
    textField_a.setVisible(false);
    add(textField_a);

    pack();
    setLocationRelativeTo(null);
    setVisible(true);
  }



  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new Test();
      }
    });
  }


}
