package Singleton.sandbox;

/*Generated by MPS */


public class TestSingleton {
  private TestSingleton instance = new TestSingleton();


  public TestSingleton getInstance() {
    return instance;
  }


  private int number = 3;
  protected String text;


  private void printHello() {
    text = "test";
  }

  public int add(int x) {
    return x + number;
  }


}
