package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AltRow_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AltRow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.AltRow";
  }
}
