package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AltView_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AltView_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.AltView";
  }
}
