package NewLanguage.behavior;

/*Generated by MPS */


public class Label_BehaviorDescriptor extends GUIElement_BehaviorDescriptor {
  public Label_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.Label";
  }
}
