package NewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LayoutRow_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public LayoutRow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "NewLanguage.structure.LayoutRow";
  }
}
