package MVCLanguage.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_4708323718295066296(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "labelName");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295654020(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("label", null);
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295216278(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "label");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295665682(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("button", null);
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295253802(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "initialText");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295675340(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return _context.createUniqueName("textField", null);
  }

  public static Object propertyMacro_GetPropertyValue_4708323718294918094(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295269756(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "visible");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718295333789(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "visible");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718294586350(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "visible");
  }

  public static Object propertyMacro_GetPropertyValue_4708323718291471138(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object referenceMacro_GetReferent_4708323718295269746(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LabelDeclaration");
  }

  public static Object referenceMacro_GetReferent_4708323718295285130(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "LabelDeclaration");
  }

  public static Object referenceMacro_GetReferent_4708323718295333779(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "ButtonDeclaration");
  }

  public static Object referenceMacro_GetReferent_4708323718295356818(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "ButtonDeclaration");
  }

  public static Object referenceMacro_GetReferent_4708323718294586340(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "TextFieldDeclaration");
  }

  public static Object referenceMacro_GetReferent_4708323718295424207(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "TextFieldDeclaration");
  }

  public static Iterable sourceNodesQuery_4708323718295067366(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "labels", true);
  }

  public static Iterable sourceNodesQuery_4708323718295217525(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "buttons", true);
  }

  public static Iterable sourceNodesQuery_4708323718295254714(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "textFields", true);
  }

  public static Iterable sourceNodesQuery_4708323718295269776(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "labels", true);
  }

  public static Iterable sourceNodesQuery_4708323718295333809(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "buttons", true);
  }

  public static Iterable sourceNodesQuery_4708323718294586370(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "textFields", true);
  }
}
