package NewLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import javax.swing.JComponent;
import javax.swing.JPanel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import javax.swing.JLabel;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class Label_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_n2z1yk_a(editorContext, node);
  }

  private EditorCell createCollection_n2z1yk_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_n2z1yk_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createJComponent_n2z1yk_a0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_n2z1yk_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_n2z1yk_c0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_n2z1yk_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_n2z1yk_e0(editorContext, node));
    return editorCell;
  }

  private EditorCell createJComponent_n2z1yk_a0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = EditorCell_Component.createComponentCell(editorContext, node, Label_Editor._QueryFunction_JComponent_n2z1yk_a0a(node, editorContext), "_n2z1yk_a0");
    editorCell.setCellId("JComponent_n2z1yk_a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }

  private static JComponent _QueryFunction_JComponent_n2z1yk_a0a(final SNode node, final EditorContext editorContext) {
    JPanel panel = new JPanel();
    String text = SPropertyOperations.getString(node, "text");

    if ((text == null || text.length() == 0)) {
      if (isEmpty_n2z1yk_a0a0d0d(SPropertyOperations.getString(node, "name"))) {
        text = "<html><i><b><font color=\"red\">Unnamed Label</font></b></i></html>";
      } else {
        text = "<html><i><b><font color=\"red\">Label " + SPropertyOperations.getString(node, "name") + "</font></b></i></html>";
      }
    }

    JLabel label = new JLabel("<html>" + SPropertyOperations.getString(node, "text") + "</html>");
    panel.add(label);

    return panel;
  }

  private EditorCell createProperty_n2z1yk_b0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_INDENT, true);
    editorCell.getStyle().putAll(style);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_n2z1yk_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "with text");
    editorCell.setCellId("Constant_n2z1yk_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_n2z1yk_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("text");
    provider.setNoTargetText("<no text>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_text");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_NEW_LINE, true);
    editorCell.getStyle().putAll(style);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_n2z1yk_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_n2z1yk_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  public static boolean isEmpty_n2z1yk_a0a0d0d(String str) {
    return str == null || str.length() == 0;
  }
}
