package ViewLanguage.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import java.awt.FlowLayout;
import javax.swing.SwingUtilities;

public class TestView extends JFrame {

  private JLabel label_a0 = new JLabel("<html>" + "<div width=50\"></div>" + "</html>");
  private JLabel label_b0 = new JLabel("<html>" + "<h1>Welcome</h1>" + "</html>");
  private JLabel label_c0 = new JLabel("<html>" + "<div width=50\"></div>" + "</html>");
  private JLabel label_a1 = new JLabel("<html>" + "<img src=\"http://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Wave.svg/55px-Wave.svg.png\">" + "</html>");
  private JLabel label_a2 = new JLabel("<html>" + "hello" + "</html>");
  private JButton button_b2 = new JButton("<html>" + "OK" + "</html>");


  public TestView() {
    setTitle("TestView");
    setLayout(new BoxLayout(this.getContentPane(), BoxLayout.Y_AXIS));
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    // Set rows 
    {
      JPanel rowPanel = new JPanel(new FlowLayout());
      rowPanel.add(label_a0);
      rowPanel.add(label_b0);
      rowPanel.add(label_c0);
      this.add(rowPanel);
    }
    {
      JPanel rowPanel = new JPanel(new FlowLayout());
      rowPanel.add(label_a1);
      this.add(rowPanel);
    }
    {
      JPanel rowPanel = new JPanel(new FlowLayout());
      rowPanel.add(label_a2);
      rowPanel.add(button_b2);
      this.add(rowPanel);
    }

    pack();
    setLocationRelativeTo(null);
    setVisible(true);
  }



  public JLabel getblank1() {
    return label_a0;
  }

  public JLabel getheadline() {
    return label_b0;
  }

  public JLabel getblank2() {
    return label_c0;
  }

  public JLabel getL1() {
    return label_a1;
  }

  public JLabel getTest() {
    return label_a2;
  }

  public JButton getbutton1() {
    return button_b2;
  }



  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        new TestView();
      }
    });
  }


}
