package ViewLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.JPanel;
import javax.swing.BoxLayout;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.awt.FlowLayout;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import javax.swing.JButton;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import javax.swing.JLabel;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.nodeEditor.cellMenu.DefaultReferenceSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class View_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_3ycbab_a(editorContext, node);
  }

  private EditorCell createCollection_3ycbab_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_3ycbab_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createCollection_3ycbab_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_3ycbab_b0(editorContext, node));
    editorCell.addEditorCell(this.createJComponent_3ycbab_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_3ycbab_d0(editorContext, node));
    editorCell.addEditorCell(this.createRefNodeList_3ycbab_e0(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_3ycbab_a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_3ycbab_a0");
    editorCell.addEditorCell(this.createConstant_3ycbab_a0a(editorContext, node));
    editorCell.addEditorCell(this.createProperty_3ycbab_b0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_3ycbab_a0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "View");
    editorCell.setCellId("Constant_3ycbab_a0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_3ycbab_b0a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_3ycbab_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_3ycbab_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createJComponent_3ycbab_c0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = EditorCell_Component.createComponentCell(editorContext, node, View_Editor._QueryFunction_JComponent_3ycbab_a2a(node, editorContext), "_3ycbab_c0");
    editorCell.setCellId("JComponent_3ycbab_c0");
    return editorCell;
  }

  private static JComponent _QueryFunction_JComponent_3ycbab_a2a(final SNode node, final EditorContext editorContext) {
    LookAndFeel usedLookAndFeel = null;

    try {
      usedLookAndFeel = UIManager.getLookAndFeel();
      UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
    } catch (Exception e) {
    }

    JPanel view = new JPanel();
    view.setLayout(new BoxLayout(view, BoxLayout.Y_AXIS));

    for (SNode row : ListSequence.fromList(SLinkOperations.getTargets(node, "rows", true))) {
      JPanel rowPanel = new JPanel(new FlowLayout());

      for (SNode elem : ListSequence.fromList(SLinkOperations.getTargets(row, "elements", true))) {
        {
          SNode button = elem;
          if (SNodeOperations.isInstanceOf(button, "ViewLanguage.structure.Button")) {
            rowPanel.add(new JButton("<html>" + SPropertyOperations.getString(button, "text") + "</html>"));
          }
        }
        {
          SNode label = elem;
          if (SNodeOperations.isInstanceOf(label, "ViewLanguage.structure.Label")) {
            rowPanel.add(new JLabel("<html>" + SPropertyOperations.getString(label, "text") + "</html>"));
          }
        }
      }

      view.add(rowPanel);
    }

    try {
      UIManager.setLookAndFeel(usedLookAndFeel);
    } catch (Exception e) {
    }

    return view;
  }

  private EditorCell createConstant_3ycbab_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_3ycbab_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createRefNodeList_3ycbab_e0(EditorContext editorContext, SNode node) {
    AbstractCellListHandler handler = new View_Editor.rowsListHandler_3ycbab_e0(node, "rows", editorContext);
    EditorCell_Collection editorCell = handler.createCells(editorContext, new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_rows");
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }

  private static class rowsListHandler_3ycbab_e0 extends RefNodeListHandler {
    public rowsListHandler_3ycbab_e0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      SNode listOwner = super.getOwner();
      return NodeFactoryManager.createNode(listOwner, editorContext, super.getElementRole());
    }

    public EditorCell createNodeCell(EditorContext editorContext, SNode elementNode) {
      EditorCell elementCell = super.createNodeCell(editorContext, elementNode);
      this.installElementCellActions(this.getOwner(), elementNode, elementCell, editorContext);
      return elementCell;
    }

    public EditorCell createEmptyCell(EditorContext editorContext) {
      EditorCell emptyCell = null;
      emptyCell = super.createEmptyCell(editorContext);
      this.installElementCellActions(super.getOwner(), null, emptyCell, editorContext);
      return emptyCell;
    }

    public void installElementCellActions(SNode listOwner, SNode elementNode, EditorCell elementCell, EditorContext editorContext) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultReferenceSubstituteInfo) {
          elementCell.setSubstituteInfo(new DefaultChildSubstituteInfo(listOwner, elementNode, super.getLinkDeclaration(), editorContext));
        }
      }
    }
  }
}
