package Singleton.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.baseLanguage.behavior.ClassConcept_Behavior;
import jetbrains.mps.baseLanguage.behavior.Classifier_Behavior;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_6109676433663731219(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6109676433665284868(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "singleton", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6109676433665195187(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "get" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "singleton", false), "name") + "Instance";
  }

  public static Object propertyMacro_GetPropertyValue_6109676433665017744(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Iterable sourceNodesQuery_6109676433663844452(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ClassConcept_Behavior.call_fields_5292274854859383272(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6109676433663883573(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return Classifier_Behavior.call_methods_5292274854859311639(_context.getNode());
  }

  public static Iterable sourceNodesQuery_6109676433665156979(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "singletons", true);
  }
}
