package Singleton.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SingletonReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SingletonReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Singleton.structure.SingletonReference";
  }
}
