package Singleton.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ClassConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Singleton_BehaviorDescriptor extends ClassConcept_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public Singleton_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "Singleton.structure.Singleton";
  }
}
