package ViewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("ViewLanguage.structure.Button").super_("ViewLanguage.structure.ViewElement").parents("ViewLanguage.structure.ViewElement").properties("text").create();
      case 1:
        return new ConceptDescriptorBuilder("ViewLanguage.structure.Label").super_("ViewLanguage.structure.ViewElement").parents("ViewLanguage.structure.ViewElement").properties("text").create();
      case 2:
        return new ConceptDescriptorBuilder("ViewLanguage.structure.View").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"rows"}, new boolean[]{true}).create();
      case 3:
        return new ConceptDescriptorBuilder("ViewLanguage.structure.ViewElement").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").abstract_().create();
      case 4:
        return new ConceptDescriptorBuilder("ViewLanguage.structure.ViewRow").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"elements"}, new boolean[]{true}).create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"ViewLanguage.structure.Button", "ViewLanguage.structure.Label", "ViewLanguage.structure.View", "ViewLanguage.structure.ViewElement", "ViewLanguage.structure.ViewRow"};
}
