package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("NewLanguage.structure.AltRow").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"elements"}, new boolean[]{true}).create();
      case 1:
        return new ConceptDescriptorBuilder("NewLanguage.structure.AltView").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"rows"}, new boolean[]{true}).create();
      case 2:
        return new ConceptDescriptorBuilder("NewLanguage.structure.Button").super_("NewLanguage.structure.GUIElement").parents("NewLanguage.structure.GUIElement").properties("text").create();
      case 3:
        return new ConceptDescriptorBuilder("NewLanguage.structure.GUI").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").properties("width", "height").children(new String[]{"rows"}, new boolean[]{true}).create();
      case 4:
        return new ConceptDescriptorBuilder("NewLanguage.structure.GUIElement").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").abstract_().create();
      case 5:
        return new ConceptDescriptorBuilder("NewLanguage.structure.Label").super_("NewLanguage.structure.GUIElement").parents("NewLanguage.structure.GUIElement").properties("text").create();
      case 6:
        return new ConceptDescriptorBuilder("NewLanguage.structure.LayoutRow").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"elements"}, new boolean[]{true}).create();
      case 7:
        return new ConceptDescriptorBuilder("NewLanguage.structure.View").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"labels", "buttons"}, new boolean[]{true, true}).create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"NewLanguage.structure.AltRow", "NewLanguage.structure.AltView", "NewLanguage.structure.Button", "NewLanguage.structure.GUI", "NewLanguage.structure.GUIElement", "NewLanguage.structure.Label", "NewLanguage.structure.LayoutRow", "NewLanguage.structure.View"};
}
