package ViewLanguage.behavior;

/*Generated by MPS */


public class Button_BehaviorDescriptor extends ViewElement_BehaviorDescriptor {
  public Button_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ViewLanguage.structure.Button";
  }
}
