package ViewLanguage.behavior;

/*Generated by MPS */


public class Label_BehaviorDescriptor extends ViewElement_BehaviorDescriptor {
  public Label_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ViewLanguage.structure.Label";
  }
}
