package ViewLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ViewRow_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ViewRow_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "ViewLanguage.structure.ViewRow";
  }
}
